/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/_utils.py:135: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and may be removed in the future. Please use keyword parameter(s) instead.
  warnings.warn(
Step 0/64000
----------
Traceback (most recent call last):
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 335, in <module>
    main()
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 330, in main
    train(run, recover=args.recover)
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 156, in train
    model_output = mvitv2s(data)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/video/mvit.py", line 549, in forward
    x = self.conv_proj(x)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 725, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 720, in _conv_forward
    return F.conv3d(
RuntimeError: Given groups=1, weight of size [96, 3, 3, 7, 7], expected input[4, 32, 3, 224, 224] to have 3 channels, but got 32 channels instead
Traceback (most recent call last):
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 335, in <module>
    main()
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 330, in main
    train(run, recover=args.recover)
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 156, in train
    model_output = mvitv2s(data)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/video/mvit.py", line 549, in forward
    x = self.conv_proj(x)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 725, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 720, in _conv_forward
    return F.conv3d(
RuntimeError: Given groups=1, weight of size [96, 3, 3, 7, 7], expected input[4, 32, 3, 224, 224] to have 3 channels, but got 32 channels instead
